version: '4'

services:
  db:
    image: postgres
    restart: always
    container_name: deepSecurity
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: postgres
      POSTGRES_DB: testjwt
    ports:
      - '5432:5432'